# Generated by Django 4.1 on 2022-09-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stock', models.IntegerField(max_length=20)),
                ('price', models.IntegerField(max_length=20)),
                ('image1', models.ImageField(blank=True, upload_to='media/post_image')),
                ('image2', models.ImageField(blank=True, upload_to='media/post_image')),
            ],
        ),
    ]
